name: time_table_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  vibration: ^3.1.3
  flutter_local_notifications: ^17.0.0 # Or latest
  shared_preferences: ^2.2.3
 
  timezone: ^0.9.2 # Or latest

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#fdf6e3"            # Cream background
  image: "lib/images/me.jpg"    # Centered photo
  android_gravity: center
  fullscreen: true
  android: true
  ios: true
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/images/screen.png"

flutter:
  uses-material-design: true
  assets:
    - lib/images/
